mysite/myapp/urls.py
from django.conf.urls import url, include
from . import views
import oauth2_provider.views as oauth2_views
from django.conf import settings
#from .views import ApiEndpoint

app_name ='myapp'














urlpatterns = [
    url(r'^index/', views.index, name='index'),
    #url(r'^hello/', views.hello, name='hello'),
    #url(r'^lms/',views.lms, name='lms'),
    url(r'^qis/',views.qis, name='qis'),
    #url(r'^login/',views.login, name='login'),
    #url(r'^settings/$',views.settings, name='settings'),
    url(r'welcome/',views.welcome, name='welcome'),
    url(r'^lms/',views.lms,name='lms'),
    #url(r'register/',views.UserFormView.as_view(), name='register'),
    #/myapp/1
   # url(r'^(?P<album_id>[0-9]+)/$', views.details, name='details'),
#/myapp/album_id/favorite
    #url(r'^(?P<album_id>[0-9]+)/favorite$', views.favorite, name='favorite'),
  ]

# Create your views here.

mysite/myapp/models.py
from django.db import models


class Album(models.Model):
    artist=models.CharField(max_length=250)
    album_title=models.CharField(max_length=500)
    genre=models.CharField(max_length=100)
    album_logo=models.CharField(max_length=1000)

    def __str__(self):
        return self.artist + " :"+ self.album_title

class Song(models.Model):
    album=models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type=models.CharField(max_length=10)
    song_title=models.CharField(max_length=250)
    is_favorite=models.BooleanField(default=False)

    def __str__(self):
        return self.song_title
# Create your models here.

mysite/myapp/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.Form):
    Username=forms.CharField(max_length=30)
    Password =forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['Username', ' Password']

mysite/myapp/views.py
from django.shortcuts import render,get_object_or_404
from django.http import Http404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from .models import Album,Song
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .forms import UserForm
from django.contrib.auth import authenticate, login
from django.views.generic import View
from django.views import generic
from oauth2_provider.views.generic import ProtectedResourceView

from social_django.models import UserSocialAuth

#http://localhost:8000/oauth/complete/github/



#
# def index(request):
#     all_albums = Album.objects.all()
#     html = ''
#     for album in all_albums:
#         url='/myapp/'+str(album.id)+'/'
#         html +='<a href="'+url+' ">'+album.album_title+'</a> <br>'
#     return HttpResponse(html)
#
# def index(request):
#     all_albums = Album.objects.all()
#     template = loader.get_template('myapp/index.html')
#     context = {'all_albums': all_albums, }
#     return HttpResponse(template.render(context, request))
# class ApiEndpoint(ProtectedResourceView):
#     def get(self, request, *args, **kwargs):
#         return HttpResponse('Hello, OAuth2!')



def index(request):
    all_albums=Album.objects.all()
    context ={'all_albums': all_albums}
    return render(request,'myapp/index.html',context)



def hello(request):
    text = """ <h1> Hello request </h1>"""
    return HttpResponse(text)

#
# def details(request, album_id):
#     try:
#         album=Album.objects.get(pk=album_id)
#     except Album.DoesNotExist:
#         raise Http404("Album doesnot exist")
#
#     return render(request, 'myapp/details.html', {'album':album})


def details(request, album_id):
    #album=Album.objects.get(pk=album_id)
    album=get_object_or_404(Album, pk=album_id)
    return render(request, 'myapp/details.html', {'album':album})
    #return HttpResponse("<h2> Album id is : " + str(album_id)+" </h2> ")


def favorite(request, album_id):
    album=get_object_or_404(Album, pk=album_id)
    try:
        selected_song=album.song_set.get(pk=request.POST['song'])
    except (KeyError, Song.DoesNotExist):




        return render(request, 'myapp/detail.html',{
        'album': album,
        'error_message': "You didnot select a valid song"

    })
    else:
        selected_song.is_favorite= True
        selected_song.save()
        return render(request, 'myapp/detail.html', {'album': album})
# Create your views here.

# class UserFormView(View):
#     form_class = UserForm
#     template_name='myapp/register.html'
# #display blank form
#     def get(self, request):
#         form=self.form_class(None)
#         return render(request, self.template_name, {'form':form})
# # process form data
#     def post(self, request):
#         form =self.form_class(request.POST)
#         #template_name ='myapp/welcome'
#         if form.is_valid():
#             user=form.save(commit=False)
#
#             #cleaned data
#
#             Username = form.cleaned_data['Username']
#             Password = form.cleaned_data['Password']
#             user.set_password(Password)
#             user.save()
#
#             # returns User Objects if credentials are correct
#
#             user=authenticate(Username=Username,Password=Password)
#             if user is not None:
#                 if user.is_active:
#                     login(request,user)
#                     return redirect('myapp:register')
#
#         return render(request, self.template_name, {'form':form})

#@login_required
def login(request):
    return render(request, 'myapp/login.html')

def welcome(request):
      return render(request,'myapp/welcome.html')



def qis(request):
#
#     form=UserForm(request.POST or None)
#     if form.is_valid():
#         user = form.save(commit=False)
#         Username  = form.cleaned_data['Username']
#         Password = form.cleaned_data['Password']
#         user.set_password(Password)
#         user.save()
#         user=authenticate(Username=Username,Password=Password)
    return render(request, 'myapp/qis.html', {'messgae':'User login in '})

def lms(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            pass  # does nothing, just trigger the validation
    else:
        form = UserForm()


    return render(request, 'myapp/lms.html', {'form':form})


def lmsextend(request):

    return render(request,'myapp/lmsextend.html')

# @login_required
# def settings(request):
#     user = request.user
#
#     try:
#         github_login = user.social_auth.get(provider='github')
#     except UserSocialAuth.DoesNotExist:
#         github_login = None
#     try:
#         twitter_login = user.social_auth.get(provider='twitter')
#     except UserSocialAuth.DoesNotExist:
#         twitter_login = None
#     try:
#         google_login = user.social_auth.get(provider='google')
#     except UserSocialAuth.DoesNotExist:
#         google_login = None
#
#     can_disconnect = (user.social_auth.count() > 1 or user.has_usable_password())
#
#     return render(request, 'myapp/settings.html', {
#         'github_login': github_login,
#         'twitter_login': twitter_login,
#         'google_login': google_login,
#         'can_disconnect': can_disconnect
#     })

mysite/myapp/templates/myapp/details.html
<div>

<img src="{{album.album_logo}}" >

</div>

<h1>{{album.album_title}}</h1>

<h3>{{album.artist}}</h3>

<!--<ul>
 {% for song in album.set.all %}
    <li>{{song.song_title}}-{{song.file_type}}</li>
{% endfor %}
</ul>-->
{% if error_message %}
<p><strong>{{  message }} </strong>/p>
{% endif %}

<form action="{% url 'music:favorite' album.id %}" method="post">
    {% csrf_token %}
    {% for song in album.song_set.all %}
        <input type="radio" id="song{{ for loop.counter }}" name="song" value="{{ song.id }}">
        <label for="song{{ for loop.counter }}">
            {{ song.song_title }}
            {% if song.is_favorite %}
                <img src="https://www.google.de/search?q=star&source=lnms&tbm=isch&sa=X&ved=0ahUKEwihh5eYvtTVAhWIORoKHRJLCfYQ_AUICigB&biw=1540&bih=760&dpr=1.25#imgrc=rGNOPLq3bwU27M:" />
            {% endif %}

        </label></form><<br>
    {% endfor %}
    <input type="submit" value="favorite">

</form>

mysite/myapp/templates/myapp/index.html
{% if all_albums %}

    <h2> Here is render</h2>
    <ul>

        {% for album in all_albums %}
            <li><a href="{%url 'myapp:details' album.id %}">{{ album.album_title}}</a></li>
           <!-- <li> <a href="/myapp/{{album.id}}/">{{album.album_title}}</a></li>-->
        {% endfor %}
    </ul>
{% else %}
    <h3> You dont have any albums </h3>

{% endif %}

mysite/myapp/templates/myapp/lms.html
{% extends 'myapp/lmsextend.html' %}
{% block content %}
<h1> Welcome to Lms page</h1>
<form method="post" action="{% url 'myapp:welcome' %}">
  {% csrf_token %}
  {{ form.as_p }}<br>
  <button type="submit">Submit</button>
</form>
<p> ---------- OR-----------------</p><br>
<a href="{% url 'social:begin' 'github' %}">Login with GitHub</a><br>
  <a href="{% url 'social:begin' 'twitter' %}">Login with Twitter</a><br>
  <a href="{% url 'social:begin' 'google-oauth2' %}"> Login with google</a>
{% endblock %}

mysite/myapp/templates/myapp/lmsextend.html
{% block content %}

<p1> Inside lms page </p1>

{% endblock %}

mysite/myapp/templates/myapp/login.html
<!--
{% block content %}
  <h2>Login</h2>
<form action="{%url 'myapp:welcome' %}" method="post" >
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
  <br>
  <p><strong>&#45;&#45; OR &#45;&#45;</strong></p>
  &lt;!&ndash;<form action="{%url 'myapp:home' %}" method="post" >&ndash;&gt;
   <a href="{% url 'social:begin' 'github' %}">Login with GitHub</a><br>
  <a href="{% url 'social:begin' 'twitter' %}">Login with Twitter</a>
  &lt;!&ndash;</form>&ndash;&gt;

{% endblock %}-->


<p> Welcome </p>

mysite/myapp/templates/myapp/qis.html
{% block content %}
<h1> QIS page FH kiel  </h1>
<form action="{% url 'myapp:welcome' %}" method="post">
{% csrf_token %}

   <label>Username </label> <input name="Username" type="text" ><br>
    <label>Password </label> <input name="Password" type="Password" ><br>
    <input type="submit" value="Submit">
</form>
<p> ---------- OR-----------------</p><br>
<a href="{% url 'social:begin' 'github' %}">Login with GitHub</a><br>
  <a href="{% url 'social:begin' 'twitter' %}">Login with Twitter</a><br>
  <a href="{% url 'social:begin' 'google-oauth2' %}"> Login with google</a>

{% endblock %}

mysite/myapp/templates/myapp/register.html
{% block content %}
<form action="{% url 'myapp/welcome' %}" method="post"></form>
{% csrf_token %}
   <label>Username </label> <input name="Username" type="text" ><br>
    <label>Password </label> <input name="Password" type="Password" ><br>
    <input type="submit" value="Submit">

{% endblock %}

mysite/myapp/templates/myapp/welcome.html
{% extends 'myapp/lmsextend.html' %}
{% block content %}


  <h2>Homepage welcome page google/twitter/ github</h2>
 <!-- <p>Hello to QIS Page  {{ user.username }} </p>
<p> {{ user.password }}</p>-->
{% endblock %}